Rails.application.config.middleware.use OmniAuth::Builder do
	provider :facebook, APP_ID, APP_SECRET
	# provider OmniAuth::Strategies::Facebook, ...
	# provider OmniAuth::Strategies::Linkedin, ...
	# provider OmniAuth::Strategies::GitHub, ...
end
